; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
src_dir = .
default_envs = mega

[custom]
mega_entry = src_mega/new_drive_and_control_test.cpp ;change this to switch what to upload

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = -<*> +<src_uno/manager_main.cpp>
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.3.0
	pololu/DualVNH5019MotorShield@^3.0.0

[env:uno_ping]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = -<*> +<src_uno/uno_ping.cpp>
monitor_speed = 115200

[env:mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<${custom.mega_entry}>
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.3.0
	pololu/DualVNH5019MotorShield@^3.0.0

[env:mega_node]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<src_mega/node_main.cpp>
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.3.0
	pololu/DualVNH5019MotorShield@^3.0.0

[env:mega_drive_encoder_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<src_mega/drive_encoder_test.cpp>
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.3.0
	pololu/DualVNH5019MotorShield@^3.0.0

[env:mega_drive_control_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<src_mega/drive_and_control_test.cpp>
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.3.0
	pololu/DualVNH5019MotorShield@^3.0.0

[env:mega_winch_control_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<src_mega/new_winch_test.cpp>
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.3.0
	pololu/DualVNH5019MotorShield@^3.0.0

[env:mega_winch_encoder_direct_i2c_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<src_mega/winch_encoder_direct_i2c_test.cpp>
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.3.0
	pololu/DualVNH5019MotorShield@^3.0.0

[env:mega_serial_motor_command_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<src_mega/serial_motor_command_test.cpp>
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.3.0
	pololu/DualVNH5019MotorShield@^3.0.0

[env:mega_digital_pin_write_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<src_mega/digital_pin_write_test.cpp>
monitor_speed = 115200

[env:mega_servo_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<src_mega/servo_test.cpp>
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.3.0
	pololu/DualVNH5019MotorShield@^3.0.0

[env:mega_contact_switch_drive_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<src_mega/contact_switch_drive_test.cpp>
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.3.0
	pololu/DualVNH5019MotorShield@^3.0.0

[env:mega_design_day_demo_controller]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<src_mega/design_day_demo_controller.cpp>
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.3.0
	pololu/DualVNH5019MotorShield@^3.0.0

[env:mega_design_day_demo_robot]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<${custom.mega_entry}>
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.3.0
	pololu/DualVNH5019MotorShield@^3.0.0

[env:mega_design_day_demo_ping_controller]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<src_mega/design_day_demo_ping_controller.cpp>
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.3.0
	pololu/DualVNH5019MotorShield@^3.0.0

[env:mega_design_day_demo_ping_robot]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<src_mega/design_day_demo_ping_robot.cpp>
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.3.0
	pololu/DualVNH5019MotorShield@^3.0.0

[env:mega_ping]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<src_mega/mega_ping.cpp>
monitor_speed = 115200

[env:mega_ping_responder]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<src_mega/mega_ping_responder.cpp>
monitor_speed = 115200
